# -*- coding: utf-8 -*-
#
# This file is part of Invenio.
# Copyright (C) 2015-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

notifications:
  email: false

sudo: false

language: python

matrix:
  fast_finish: true
  allow_failures:
    - env: REQUIREMENTS=devel

cache:
  - pip

env:
  - REQUIREMENTS=lowest
  - REQUIREMENTS=release DEPLOY=true
  - REQUIREMENTS=devel

python:
  - "2.7"
  - "3.5"


before_install:
  - "nvm install 6; nvm use 6"
  - "travis_retry pip install --upgrade pip setuptools py"
  - "travis_retry pip install twine wheel coveralls requirements-builder"
  - "requirements-builder --level=min setup.py > .travis-lowest-requirements.txt"
  - "requirements-builder --level=pypi setup.py > .travis-release-requirements.txt"
  - "requirements-builder --level=dev --req requirements-devel.txt setup.py > .travis-devel-requirements.txt"

install:
  - "travis_retry pip install -r .travis-${REQUIREMENTS}-requirements.txt"
  - "travis_retry pip install -e .[all]"

script:
  - "./run-tests.sh"

after_success:
  - coveralls

deploy:
  provider: pypi
  user: inveniosoftware
  password:
    secure: "WfmCp0HTnEJo+ch5dHUtayTSde1E4JaaB44/8YdGLqs1Ou64oN7AmM+vxSVgdBXQKswP/aPTgHOgklb8Rc1wBPdY6Zcz53R7pKd+uum1Bz1OLhmSzYa5FfeVqw3iKrn+eRh4tmzZuUMC2lUaBHG5u/mAV7uQm781/SaPEacWlpRe0KM96O8xVu5RJ70ScREAaT9AFbrJVIZS7w3QtBuFbBlH8WUYxVgPlOU/6UMxQcKCzEYdot7jFeedO9xa5nPZDrxCPDqkdp/2zVkspOc/Bd4eFgCYYXuDVGjeTA+01MQ1Gns1S+XPu1hSFlggarTSKJFYrUKqXinUvnWFFnFqCt5FSLg28YCSxCgL3wzhexi/52W1mEjxZlrNmEDU3CYKAU5InEYgFYS+TjBQu905pjWxOmRE5R9Iyg7y8WqhEB2HyRwR8jhZ3FH9CuoRQRkjGAVizZkEoGTLbHEN+bGe3p+7DIYlCfSbl/Jvy4V4iObE9FgO0kCCjHJVaBP0uNle+SfeT3e8ekk+Z60lwn3OTaBMqvqxBrt9rWwwVDaeWTvRVT9agblxJfZ/jDpOAiz8azhFhQzdMytBs83iEFgxQu+5GDbvxrrGQpbfx/NCTPqxwkAjXFkj384ropgYPxzzq5zgp9rnzpeRTNUBBVssGQfhQsPbq/4RlxjbH3VroA8="
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    python: "2.7"
    repo: inveniosoftware/invenio-base
    condition: $DEPLOY = true
